export const ADD_TODO = "ADD_TODO";
export const TOGGLE_TODO = "TOGGLE_TODO";
export const SET_FILTER = "SET_FILTER";

export const SET_NOTIFICATIONS = 'SET_NOTIFICATIONS'
export const SET_LOGGED_IN = 'SET_LOGGED_IN'
export const SET_LOGGED_OUT = 'SET_LOGGED_OUT'
export const SET_EXPIRED_SESSION = 'SET_EXPIRED_SESSION'
export const SET_LOGGED_UP = 'SET_LOGGED_UP'
export const SET_PASSWORD_RECOVERY = 'SET_PASSWORD_RECOVERY'

export const GET_PERMISSIONS = 'GET_PERMISSIONS'

export const GET_ROLES = 'GET_ROLES'
export const GET_ROLE = 'GET_ROLE'
export const PUT_ROLE = 'PUT_ROLE'
export const POST_ROLE = 'POST_ROLE'
export const DELETE_ROLE = 'DELETE_ROLE'

export const GET_DEPARTMENTS = 'GET_DEPARTMENTS'
export const GET_DEPARTMENT = 'GET_DEPARTMENT'
export const PUT_DEPARTMENT = 'PUT_DEPARTMENT'
export const POST_DEPARTMENT = 'POST_DEPARTMENT'
export const DELETE_DEPARTMENT = 'DELETE_DEPARTMENT'